export const umkm = [
  {
    name: "UMKM 1",
    img: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo, obcaecati similique. Cumque aspernatur dolorem eos culpa molestiae, veritatis ad sit!",
    id: 1,
  },
  {
    name: "UMKM 2",
    img: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo, obcaecati similique. Cumque aspernatur dolorem eos culpa molestiae, veritatis ad sit!",
    id: 2,
  },
];

export const wisata = [
  {

  },
  {

  },
]

export const usaha = [
  // {
  //   id: 1,
  //   subLink: "andri-roasting",
  //   title: "Andri Roasting",
  //   category: "kopi",
  //   subCategory: ["jasa roasting", "boga", "industri rumah"],
  //   owner: "Mas Andri",
  //   address: "RT 02 RW 07, Dusun Kerep, Desa Gemawang",
  //   gmaps: "https://goo.gl/maps/XMt8VyhjZvouk3nJ9",
  //   phone: "08587054072",
  //   product: "Kopi bubuk dan jasa roasting biji kopi",
  //   price: "Jasa roasting kopi Rp10.000/kg dan jual bubuk kopi robusta Rp60.000/kg",
  //   firstParagraph:
  //     "Andri Roasting adalah salah satu UMKM (Usaha Mikro Kecil Menengah) yang bergerak dalam bidang makanan, tepatnya pada jasa roasting kopi dan pembuatan kopi bubuk jenis robusta. Mas Andri sebagai owner bercerita bahwa awal mula beliau menekuni bidang perkopian adalah lantaran tertarik saat melihat video di Youtube.",
  //   secondParagraph:
  //     "Mesin roasting yang digunakan adalah mesin DIY (Do it Yourself) alias handmade. Beliau mempergunakan dandang bakso sebagai tempat cooling biji kopi seusai proses roasting. Biji kopi yang digunakan berasal dari hasil kebun pribadi maupun pembelian dari wilayah lain. Urutan produksi yang dilakukan adalah melalui tahapan roasting, grinding, dan pengemasan menggunakan plastik pouch zipper. Produk yang dihasilkan biasanya dipasarkan di angkringan terdekat.",
  //   authorName: "Tim KKN Jambu JT092",
  //   authorAvatar: "/assets/images/logo.png",
  //   createdAt: "07 Juli, 2022",
  //   cover: "/assets/images/UMKM/Andri_Roasting.jpeg",
  // },
  // {
  //   id: 2,
  //   subLink: "madu-aneka-sari",
  //   title: "Madu Aneka Sari",
  //   category: "madu",
  //   subCategory: ["madu", "royal jelly", "bee pollen"],
  //   owner: "Edy Sumarmo",
  //   address: "RT 03 RW 01, Dusun Krajan, Desa Gemawang",
  //   gmaps: "https://goo.gl/maps/7jWSEcka8NL8zqsP9",
  //   phone: "085726895878",
  //   product: "Madu kelengkeng, madu randu, dan tepung sari",
  //   price: "Rp150.000-500.000/botol",
  //   firstParagraph:
  //     "Madu Aneka Sari adalah salah satu UMKM (Usaha Mikro Kecil Menengah) Dusun Krajan yang didirikan oleh Bapak Edy Sumarmo. Dilihat dari namanya saja, sudah terbayang jelas dalam pikiran bahwa UMKM ini menawarkan madu sebagai produk utamanya. Pada mulanya, Bapak Edy Sumarmo adalah seorang peternak madu/lebah atau jika menggunakan istilah Desa Gemawang, “penggembala lebah”. Beliau menjalani profesi tersebut sejak tahun 1979-1986 sebelum akhirnya berjualan madunya. Mulai tahun tersebut pula, madu yang diperjualkan bukanlah madu hasil ternakan sendiri melainkan impor dari berbagai wilayah bahkan hingga sejauh Australia.",
  //   secondParagraph:
  //     "Madu yang dijual pun beraneka macam, mulai dari madu kelengkeng, rambutan, randu, karet, polen, kaliandra, durian, dan tepung sari. Harga produknya pun bervariasi. Mulai dari Rp150.000 hingga Rp500.000. Hingga saat ini, Pak Edy belum memasarkan produknya melalui toko daring lantaran kerentanan wadah madu yang mengkhawatirkan. Pemesanan dapat dilakukan melalui kontak yang telah diberikan pada awal artikel ini, website Madu Aneka Sari,  maupun mengunjungi kios beliau secara langsung yang berdiri tegak di jalan Magelang-Ambarawa.",
  //   authorName: "Tim KKN Jambu JT092",
  //   authorAvatar: "/assets/images/logo.png",
  //   createdAt: "12 Juli, 2022",
  //   cover: "/assets/images/UMKM/Aneka_Sari.jpeg",
  // },
  {
    id: 1,
    subLink: "hafara-shoes",
    title: "Hafara",
    category: "fashion",
    subCategory: ["sepatu batik", "sandal batik", "kerajinan"],
    owner: "Nurochmi",
    address: "RT 01 RW 07, Dusun Kerep, Desa Gemawang",
    gmaps: "https://goo.gl/maps/aXgpJ8waQDEuLB4J8",
    ecommerce: "Nurochmi Hafara (Facebook), Hafarashoes.id (Instagram)",
    phone: "085865090072",
    product: "Sepatu dan sandal batik",
    price: "Rp150.000-180.000",
    firstParagraph:
      "Terletak di Dusun Kerep, Hafara adalah salah satu usaha yang berfokus pada bidang fashion, tepatnya pada sepatu batik. Sepatu batik yang dibuat dapat dipesan melalui berbagai platform seperti Facebook, Instagram, maupun Whatsapp. Summer dan Pam adalah contoh merek sol yang digunakan oleh Ibu Nurochmi kala membuat produknya. Pewarna yang digunakan terdiri dari dua macam yakni alami dan sintetis. Nurochmi selaku pemilik menjelaskan bahwa pewarna alami meskipun warnanya tidak terlalu nyentrik atau mencolok, memiliki daya tahan warna yang lama (re: tidak gampang kusam). Sebaliknya, pewarna sintetis yang memiliki warna mencolok justru lebih mudah kusam maupun “kabur”.",
    secondParagraph:
      "Harga yang ditawarkan oleh Hafara sangat terjangkau. Sepatu-sepatu yang menawarkan kearifan lokal namun tetap memiliki kesan premium ini dijual pada kisaran Rp120.000,00 hingga Rp180.000,00. Selain membeli berbagai produk yang sudah jadi dan dipajang pada etalase, konsumen juga diperbolehkan untuk me-request sesuai keinginan. Konsumen juga dapat membawa sendiri kain maupun motif batik yang diinginkan. Lokasi UMKM (Usaha Mikro, Kecil, dan Menengah) Hafara sudah tertera di Google Maps dengan kata kunci “Sepatu Batik Hafara” dan dapat dijangkau menggunakan sepeda motor.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "15 Juli, 2022",
    cover: "/assets/images/UMKM/Hafara.jpeg",
  },
  {
    id: 2,
    subLink: "kopi-pandan-wangie",
    title: "Kopi Pandan Wangie",
    category: "kopi",
    subCategory: ["kopi", "minuman", "robusta"],
    owner: "Hafri Samsuri",
    address: "RT 01 RW 02, Dusun Banaran, Desa Gemawang",
    gmaps: "https://goo.gl/maps/4dFtUwmZPSzk1RkT7",
    ecommerce: "KOPANWABA (Tokopedia)",
    phone: "081326078070",
    product: "Kopi robusta bubuk",
    price: "Rp5.000-80.000",
    firstParagraph:
      "Kopi Pandan Wangie adalah salah satu usaha kopi bubuk yang berdiri di Desa Gemawang, tepatnya pada Dusun Banaran. Pak Hafri Samsuri menjelaskan bahwa biji kopi yang digunakan dalam membuat kopi bubuk berasal dari kebun sendiri maupun membeli ke pengepul apabila stok biji kopi dari kebun habis. Peralatan yang digunakan oleh Pak Hafri dalam mengolah kopinya adalah handmade atau buatan sendiri. Alat yang dibuat sendiri dan digunakan diantaranya adalah mesin roasting dan grinder biji kopi. Alat-alat tersebut dibuat oleh ayah Pak Hafri dan kemudian dilanjutkan penggunaannya oleh Pak Hafri.",
    secondParagraph:
      "Produk kopi yang ditawarkan oleh Pandan Wangie adalah bubuk kopi robusta yang dikemas menggunakan alumunium foil dan diberikan plastik pada bagian luarnya agar aman dari hujan. Kopi bubuk tersebut dipasarkan pada berbagai tempat seperti angkringan, toko kelontong, hingga karyawan PTP. Selain itu, tentunya pemesanan melalui Tokopedia dan Whatsapp juga berlaku. Produk yang dipasarkan sudah mendapat izin PIRT sehingga kualitasnya terjamin.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "17 Juli, 2022",
    cover: "/assets/images/UMKM/Kopi_Pandan_Wangie.jpeg",
  },
  {
    id: 3,
    subLink: "arizqi-craft",
    title: "Arizqi Craft",
    category: "kerajinan",
    subCategory: ["tas", "dompet", "kerajinan tangan"],
    owner: "Nur Khamami",
    address: "RT 01 RW 05, Dusun Selo, Desa Gemawang",
    gmaps: "https://goo.gl/maps/cDeo3SsFKFa5Mefh7",
    ecommerce: "Arizqi Craft (Facebook), arizqicraft (Instagram)",
    phone: "082300144405",
    product: "Tas, dompet, dan souvenir",
    price: "Rp2.000-150.000",
    firstParagraph:
      "Arizqy adalah salah satu UMKM (Usaha Mikro, Kecil, dan Menengah) yang berfokus pada bidang fashion, terkhusus tas, dompet, dan souvenir. UMKM ini terletak pada Dusun Selo, RT 01 RW 05, Gemawang. Ibu Nur Khamami sebagai pemilik awalnya mengikuti pelatihan menjahit hingga kemudian beralih membuka usaha jahit sendiri.",
    secondParagraph:
      "Konsumen dipersilahkan untuk memesan produk Arizqy menggunakan metode custom sesuka selera. Harga yang ditawarkan pada UMKM Arizqy juga terjangkau. Ibu Nur juga memasarkan produknya pada berbagai tempat seperti pasar maupun toko-toko swalayan dimana kemungkinan munculnya konsumen cukup besar.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "17 Juli, 2022",
    cover: "/assets/images/UMKM/Arizqi.JPG",
  },
  {
    id: 4,
    subLink: "shaqueena-bejo",
    title: "Shaqueena Bejo",
    category: "minuman",
    subCategory: ["minuman", "rempah", "tradisional"],
    owner: "Nur Khamami",
    address: "RT 01 RW 08, Dusun Guyang Warak, Desa Gemawang",
    gmaps: "https://goo.gl/maps/xqYsMQvbsZmhRNKPA",
    ecommerce: "Shaquenabejo (Tokopedia), shaquenabejo (Bukalapak), Shaquena (Facebook), Shaquena (Instagram)",
    phone: "085728040034",
    product: "Wedang uwuh",
    price: "Rp30.000/pak (10 pcs)",
    firstParagraph:
      "Salah satu usaha yang menawarkan produk berupa minuman adalah Shaqueena. Minuman yang ditawarkan adalah wedang uwuh. Pak Bejo selaku pemilik Shaqueena menjelaskan bahwa asal nama usahanya berasal dari nama anaknya. Awal mula pak Bejo memulai usahanya adalah tahun 2017. Bahan-bahan yang digunakan dalam wedang uwuh Shaqueena adalah kayu secang, rondong, cengkeh, gagang cengkeh, kapulaga, jahe, dan gula batu.",
    secondParagraph:
      "Pak Bejo memasarkan produknya pada beberapa tempat seperti Cafe Banaran, Kopi Eva, Soto Sedep, Condong Raos, Ungaran, dan Semilir. Produk beliau dipasarkan dengan harga terjangkau yakni Rp30.000 per pak.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "19 Juli, 2022",
    cover: "/assets/images/UMKM/",
  },
  {
    id: 5,
    subLink: "rosali-fashion",
    title: "Rosali Fashion",
    category: "fashion",
    subCategory: [],
    owner: "Yuliyati",
    address: "RT 01 RW 08, Dusun Guyang Warak, Desa Gemawang",
    gmaps: "https://goo.gl/maps/xqYsMQvbsZmhRNKPA",
    ecommerce: "-",
    phone: "085325088112",
    product: "Jasa jahit",
    price: "Tergantung kesulitan pesanan",
    firstParagraph:
      "",
    secondParagraph:
      "",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "21 Juli, 2022",
    cover: "/assets/images/UMKM/",
  },
  {
    id: 6,
    subLink: "kayu-anugerah",
    title: "Anugerah Kreatif",
    category: "Tukang kayu",
    subCategory: ["Pengrajin kotak lebah"],
    owner: "Hartanto",
    address: "RT 03 RW 03, Dusun Banaran, Desa Gemawang",
    gmaps: "https://goo.gl/maps/TEuHPEgeHgjuv69bA",
    ecommerce: "-",
    phone: "082322885852",
    product: "Kotak lebah dan pesanan meubel",
    price: "Rp150.000/kotak",
    firstParagraph:
      "Kayu Anugerah Kreatif adalah salah satu UMKM (Usaha Mikro, Kecil, dan Menengah) yang bergerak dalam bidang craft. Pak Hartanto sebagai pemilik menjelaskan bahwa usahanya memiliki fokus utama pada pembuatan boks sarang lebah. Usaha ini telah berdiri sejak tahun 2006 dan menurut pemilik, mengalami peningkatan order yang signifikan pada masa pandemi. Hal ini dapat dimengerti karena ketika pandemi Covid-19, manusia jarang keluar rumah dan berinteraksi dengan alam. Dalam kondisi demikian, alam memiliki keleluasaan untuk merevitalisasi dirinya. Para peternak lebah tentunya melihat ini sebagai kesempatan untuk mengembangkan bisnisnya yang pada gilirannya berimbas pada jumlah permintaan boks lebah.",
    secondParagraph:
      "Pak Hartanto memasarkan produknya melalui Whatsapp dan mulut ke mulut. Pangsa pasar Kayu Anugerah Kreatif sudah menjangkau berbagai wilayah seperti Kediri, Blitar, dan Banyuwangi. Satu boks lebah dipasarkan seharga Rp150.000,00. Selain boks lebah, Kayu Anugerah Kreatif juga menerima orderan mebel yang lain seperti gerobak bakso, lemari, kursi, maupun meja. Bahan dasar pembuatan berbagai macam perkakas tersebut adalah kayu surian yang diklaim mampu bertahan hingga 5-10 tahun dan kayu pinus yang mampu bertahan hingga 3 tahun. Peralatan yang digunakan oleh Pak Hartanto adalah peralatan modern sehingga mempermudah pekerjaannya. Dalam sebulan, beliau mampu menyelesaikan hingga 500 buah boks lebah. Konsumen dapat langsung datang dan berbincang dengan Pak Hartanto di workshop-nya yang terletak di RT 03 RW 03 Banaran, Desa Gemawang.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: " Juli, 2022",
    cover: "/assets/images/UMKM/",
  },
  // {
  //   id: ,
  //   subLink: "",
  //   title: "",
  //   category: "",
  //   subCategory: ["", "", ""],
  //   owner: "",
  //   address: "",
  //   gmaps: "",
  //   ecommerce: "",
  //   phone: "",
  //   product: "",
  //   price: "",
  //   firstParagraph:
  //     "",
  //   secondParagraph:
  //     "",
  //   authorName: "Tim KKN Jambu JT092",
  //   authorAvatar: "/assets/images/logo.png",
  //   createdAt: " Juli, 2022",
  //   cover: "/assets/images/UMKM/",
  // },
];
