export const umkm = [
  {
    name: "UMKM 1",
    img: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo, obcaecati similique. Cumque aspernatur dolorem eos culpa molestiae, veritatis ad sit!",
    id: 1,
  },
  {
    name: "UMKM 2",
    img: "",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo, obcaecati similique. Cumque aspernatur dolorem eos culpa molestiae, veritatis ad sit!",
    id: 2,
  },
];

export const usaha = [
  {
    id: 1,
    subLink: "hafara-shoes",
    title: "Hafara",
    category: "fashion",
    subCategory: ["sepatu batik", "sandal batik", "kerajinan"],
    owner: "Nurochmi",
    address: "RT 01 RW 07, Dusun Kerep, Desa Gemawang",
    gmaps: "https://goo.gl/maps/aXgpJ8waQDEuLB4J8",
    ecommerce: "Nurochmi Hafara (Facebook), Hafarashoes.id (Instagram)",
    phone: "085865090072",
    product: "Sepatu dan sandal batik",
    price: "Rp150.000-180.000",
    firstParagraph:
      "Terletak di Dusun Kerep, Hafara adalah salah satu usaha yang berfokus pada bidang fashion, tepatnya pada sepatu batik. Sepatu batik yang dibuat dapat dipesan melalui berbagai platform seperti Facebook, Instagram, maupun Whatsapp. Summer dan Pam adalah contoh merek sol yang digunakan oleh Ibu Nurochmi kala membuat produknya. Pewarna yang digunakan terdiri dari dua macam yakni alami dan sintetis. Nurochmi selaku pemilik menjelaskan bahwa pewarna alami meskipun warnanya tidak terlalu nyentrik atau mencolok, memiliki daya tahan warna yang lama (re: tidak gampang kusam). Sebaliknya, pewarna sintetis yang memiliki warna mencolok justru lebih mudah kusam maupun “kabur”.",
    secondParagraph:
      "Harga yang ditawarkan oleh Hafara sangat terjangkau. Sepatu-sepatu yang menawarkan kearifan lokal namun tetap memiliki kesan premium ini dijual pada kisaran Rp120.000,00 hingga Rp180.000,00. Selain membeli berbagai produk yang sudah jadi dan dipajang pada etalase, konsumen juga diperbolehkan untuk me-request sesuai keinginan. Konsumen juga dapat membawa sendiri kain maupun motif batik yang diinginkan. Lokasi UMKM (Usaha Mikro, Kecil, dan Menengah) Hafara sudah tertera di Google Maps dengan kata kunci “Sepatu Batik Hafara” dan dapat dijangkau menggunakan sepeda motor.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "15 Juli, 2022",
    cover: "/assets/images/UMKM/Hafara.jpeg",
  },
  {
    id: 2,
    subLink: "kopi-pandan-wangie",
    title: "Kopi Pandan Wangie",
    category: "kopi",
    subCategory: ["kopi", "minuman", "robusta"],
    owner: "Hafri Samsuri",
    address: "RT 01 RW 02, Dusun Banaran, Desa Gemawang",
    gmaps: "https://goo.gl/maps/4dFtUwmZPSzk1RkT7",
    ecommerce: "KOPANWABA (Tokopedia)",
    phone: "081326078070",
    product: "Kopi robusta bubuk",
    price: "Rp5.000-80.000",
    firstParagraph:
      "Kopi Pandan Wangie adalah salah satu usaha kopi bubuk yang berdiri di Desa Gemawang, tepatnya pada Dusun Banaran. Pak Hafri Samsuri menjelaskan bahwa biji kopi yang digunakan dalam membuat kopi bubuk berasal dari kebun sendiri maupun membeli ke pengepul apabila stok biji kopi dari kebun habis. Peralatan yang digunakan oleh Pak Hafri dalam mengolah kopinya adalah handmade atau buatan sendiri. Alat yang dibuat sendiri dan digunakan diantaranya adalah mesin roasting dan grinder biji kopi. Alat-alat tersebut dibuat oleh ayah Pak Hafri dan kemudian dilanjutkan penggunaannya oleh Pak Hafri.",
    secondParagraph:
      "Produk kopi yang ditawarkan oleh Pandan Wangie adalah bubuk kopi robusta yang dikemas menggunakan alumunium foil dan diberikan plastik pada bagian luarnya agar aman dari hujan. Kopi bubuk tersebut dipasarkan pada berbagai tempat seperti angkringan, toko kelontong, hingga karyawan PTP. Selain itu, tentunya pemesanan melalui Tokopedia dan Whatsapp juga berlaku. Produk yang dipasarkan sudah mendapat izin PIRT sehingga kualitasnya terjamin.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "17 Juli, 2022",
    cover: "/assets/images/UMKM/Kopi_Pandan_Wangie.jpeg",
  },
  {
    id: 3,
    subLink: "arizqi-craft",
    title: "Arizqi Craft",
    category: "kerajinan",
    subCategory: ["tas", "dompet", "kerajinan tangan"],
    owner: "Nur Khamami",
    address: "RT 01 RW 05, Dusun Selo, Desa Gemawang",
    gmaps: "https://goo.gl/maps/cDeo3SsFKFa5Mefh7",
    ecommerce: "Arizqi Craft (Facebook), arizqicraft (Instagram)",
    phone: "082300144405",
    product: "Tas, dompet, dan souvenir",
    price: "Rp2.000-150.000",
    firstParagraph:
      "Arizqy adalah salah satu UMKM (Usaha Mikro, Kecil, dan Menengah) yang berfokus pada bidang fashion, terkhusus tas, dompet, dan souvenir. UMKM ini terletak pada Dusun Selo, RT 01 RW 05, Gemawang. Ibu Nur Khamami sebagai pemilik awalnya mengikuti pelatihan menjahit hingga kemudian beralih membuka usaha jahit sendiri.",
    secondParagraph:
      "Konsumen dipersilahkan untuk memesan produk Arizqy menggunakan metode custom sesuka selera. Harga yang ditawarkan pada UMKM Arizqy juga terjangkau. Ibu Nur juga memasarkan produknya pada berbagai tempat seperti pasar maupun toko-toko swalayan dimana kemungkinan munculnya konsumen cukup besar.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "17 Juli, 2022",
    cover: "/assets/images/UMKM/Arizqi.JPG",
  },
  {
    id: 4,
    subLink: "shaquena-bejo",
    title: "Shaquena Bejo",
    category: "minuman",
    subCategory: ["minuman", "rempah", "tradisional"],
    owner: "Partiman",
    address: "RT 01 RW 08, Dusun Guyang Warak, Desa Gemawang",
    gmaps: "https://goo.gl/maps/xqYsMQvbsZmhRNKPA",
    ecommerce: "Shaquenabejo (Tokopedia), shaquenabejo (Bukalapak), Shaquena (Facebook), Shaquena (Instagram)",
    phone: "085728040034",
    product: "Wedang uwuh",
    price: "Rp30.000/pak (10 pcs)",
    firstParagraph:
      "Salah satu usaha yang menawarkan produk berupa minuman adalah Shaqueena. Minuman yang ditawarkan adalah wedang uwuh. Pak Bejo selaku pemilik Shaqueena menjelaskan bahwa asal nama usahanya berasal dari nama anaknya. Awal mula pak Bejo memulai usahanya adalah tahun 2017. Bahan-bahan yang digunakan dalam wedang uwuh Shaqueena adalah kayu secang, rondong, cengkeh, gagang cengkeh, kapulaga, jahe, dan gula batu.",
    secondParagraph:
      "Pak Bejo memasarkan produknya pada beberapa tempat seperti Cafe Banaran, Kopi Eva, Soto Sedep, Condong Raos, Ungaran, dan Semilir. Produk beliau dipasarkan dengan harga terjangkau yakni Rp30.000 per pak.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "19 Juli, 2022",
    cover: "/assets/images/UMKM/Shaquena.png",
  },
  {
    id: 5,
    subLink: "rosali-fashion",
    title: "Rosali Fashion",
    category: "fashion",
    subCategory: [],
    owner: "Yuliyati",
    address: "RT 01 RW 08, Dusun Guyang Warak, Desa Gemawang",
    gmaps: "https://goo.gl/maps/xqYsMQvbsZmhRNKPA",
    ecommerce: "-",
    phone: "085325088112",
    product: "Jasa jahit",
    price: "Mulai dari Rp50.000",
    firstParagraph:
      "Rosali Fashion yang berlokasi di Dusun Guyang Warak adalah usaha yang berfokus pada bidang sandang. Ibu Yuliyati, sebagai pemilik, mengungkapkan bahwa nama Rosali adalah nama anaknya yang kemudian diadopsi sebagai nama usahanya. Produk yang dihasilkan oleh Rosali Fashion diantaranya adalah gamis, kemeja, celana, baju koko, pakaian anak-anak maupun pakaian wanita.",
    secondParagraph:
      "Sistem pemasaran yang diimplementasikan oleh Rosali Fashion adalah pre-order. Bahan yang dipergunakan didapat dari rekan kerja maupun dicari secara mandiri. Ibu Yuliyati mengerjakan berbagai pesanan yang datang sendirian. Akan tetapi, jika suatu saat pesanan yang datang berjumlah banyak, maka beliau akan mengerjakannya bersama rekannya. Harga yang dipatok oleh Rosali Fashion berkisar mulai Rp50.000,00 untuk hem atau kemeja dan Rp70.000,00 hingga Rp80.000,00 untuk gamis. Ukuran yang tersedia adalah S, M, dan L. Pesanan yang sering menghampiri pintu rumah beliau adalah pesanan dari SD maupun baju koko ketika Bulan Ramadhan. Customer dapat langsung mengunjungi rumah beliau di Dusun Guyang Warak RT 01 RW 08.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "21 Juli, 2022",
    cover: "/assets/images/UMKM/",
  },
  {
    id: 6,
    subLink: "kayu-anugerah",
    title: "Anugerah Kreatif",
    category: "Pengrajin kayu",
    subCategory: ["Pengrajin kotak lebah"],
    owner: "Hartanto",
    address: "RT 03 RW 03, Dusun Banaran, Desa Gemawang",
    gmaps: "https://goo.gl/maps/TEuHPEgeHgjuv69bA",
    ecommerce: "-",
    phone: "082322885852",
    product: "Kotak lebah dan pesanan meubel",
    price: "Rp150.000/kotak",
    firstParagraph:
      "Kayu Anugerah Kreatif adalah salah satu UMKM (Usaha Mikro, Kecil, dan Menengah) yang bergerak dalam bidang craft. Pak Hartanto sebagai pemilik menjelaskan bahwa usahanya memiliki fokus utama pada pembuatan boks sarang lebah. Usaha ini telah berdiri sejak tahun 2006 dan menurut pemilik, mengalami peningkatan order yang signifikan pada masa pandemi. Hal ini dapat dimengerti karena ketika pandemi Covid-19, manusia jarang keluar rumah dan berinteraksi dengan alam. Dalam kondisi demikian, alam memiliki keleluasaan untuk merevitalisasi dirinya. Para peternak lebah tentunya melihat ini sebagai kesempatan untuk mengembangkan bisnisnya yang pada gilirannya berimbas pada jumlah permintaan boks lebah.",
    secondParagraph:
      "Pak Hartanto memasarkan produknya melalui Whatsapp dan mulut ke mulut. Pangsa pasar Kayu Anugerah Kreatif sudah menjangkau berbagai wilayah seperti Kediri, Blitar, dan Banyuwangi. Satu boks lebah dipasarkan seharga Rp150.000,00. Selain boks lebah, Kayu Anugerah Kreatif juga menerima orderan mebel yang lain seperti gerobak bakso, lemari, kursi, maupun meja. Bahan dasar pembuatan berbagai macam perkakas tersebut adalah kayu surian yang diklaim mampu bertahan hingga 5-10 tahun dan kayu pinus yang mampu bertahan hingga 3 tahun. Peralatan yang digunakan oleh Pak Hartanto adalah peralatan modern sehingga mempermudah pekerjaannya. Dalam sebulan, beliau mampu menyelesaikan hingga 500 buah boks lebah. Konsumen dapat langsung datang dan berbincang dengan Pak Hartanto di workshop-nya yang terletak di RT 03 RW 03 Banaran, Desa Gemawang.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "23 Juli, 2022",
    cover: "/assets/images/UMKM/",
  },
  {
    id: 7,
    subLink: "ropi-garmen",
    title: "Ropi Garmen",
    category: "Fashion",
    subCategory: ["Jasa jahit", "Pakaian", "Seragam"],
    owner: "Isrofi",
    address: "RT 02 RW 07, Dusun Kerep, Desa Gemawang",
    gmaps: "",
    ecommerce: "-",
    phone: "085848837017",
    product: "Jasa jahit",
    price: "Rp50.000 untuk hem lengan pendek dan Rp70.000-80.000 untuk hem lengan panjang",
    firstParagraph:
      "Namanya adalah Isrofi, seorang penjahit kondang asal Desa Gemawang. Inspirasi awal Pak Ropi dalam menjahit adalah karena dulu beliau menginginkan baju akan tetapi saat itu belum memiliki uang. Dengan keinginan yang kuat, beliau belajar kepada tetangganya bagaimana cara menjahit. Berawal dari situ, beliau terus menambah kemampuannya terkait urusan jahit-menjahit melalui seminar yang diikuti.",
    secondParagraph:
      "Beliau memasarkan jasa jahitnya secara langsung kepada instansi-instansi yang memiliki potensi. Pemesanan jasa beliau dapat dilakukan melalui WhatsApp maupun datang langsung ke workshop-nya di Dusun Kerep RT 02 RW 07. Ropi Garmen sanggup membuatkan berbagai macam pakaian, mulai dari celana, hem, jas, maupun kemeja biasa. Dalam menjalankan usahanya, beliau merekrut teman-temannya dan menjalin hubungan kerjasama mutualisme yang apik. Jasa jahit Ropi Garmen terhitung murah meski tetap mengambil patokan dari jenis dan kain baju yang diinginkan. Beliau berkali-kali menekankan untuk meningkatkan mental karena sangatlah penting bagi kemajuan karir. Saat ini, berkat usaha, doa, dan mental beliau yang kuat, Ropi Garmen menerima banyak pesanan penting dari berbagai tempat seperti Puskesmas, KORPRI, kampus, sekolah, maupun pesanan pribadi. Jasa jahit beliau patut diperhitungkan apabila mencari penjahit yang mampu membuatkan pakaian dengan ukuran pas.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "26 Juli, 2022",
    cover: "/assets/images/UMKM/Ropi_Garmen.jpeg",
  },
  {
    id: 8,
    subLink: "yu-ani-cake",
    title: "Yu Ani Cake and Cookies",
    category: "Kue",
    subCategory: ["Makanan", "Dessert"],
    owner: "Ani",
    address: "RT 01 RW 03, Dusun Banaran, Desa Gemawang",
    gmaps: "https://goo.gl/maps/AN4VatusjGBynE3d8",
    ecommerce: "yuu_anii (Instagram)",
    phone: "088980880322/083150191155",
    product: "Kue custom dan kue kering",
    price: "Mulai dari Rp25.000",
    firstParagraph:
      "Yu Ani Cake adalah satu-satunya UMKM Desa Gemawang yang memiliki spesialisasi pada bidang cake atau kue. Mbak Ani sebagai pemilik mengakui bahwa beliau sudah senang membuat kue sejak kecil. Latihan bertahun-tahun yang dijalankan sekaligus sebagai hobi memampukan Mbak Ani untuk membuka usaha ini. Awal mula kemunculan usaha ini adalah pada tahun 2019 ketika Mbak Ani dimintai tolong untuk membuat kue ulang tahun. Dengan hasil yang baik, beliau mencoba peruntungannya dengan mempromosikan kuenya dan terbukti berhasil hingga mampu berlanjut hingga sekarang.",
    secondParagraph:
      "Pemasaran kue buatan Mbak Ani dapat dilihat sekaligus dipesan melalui Instagram maupun WhatsApp beliau. Selain kue, Yu Ani Cake juga menerima pesanan brownies dan aneka kue kering seperti nastar, kastengel, kacang, dan putri salju. Berbagai alat seperti mixer, oven, squid, dan selainnya sudah tersedia sebagai senjata Mbak Ani untuk menggeluti usahanya. Harga produk yang dipasarkan mulai dari Rp25.000,00. Rumah Mbak Ani terletak pada RT 01 RW 03 Dusun Banaran, Desa Gemawang dan dapat dengan mudah dicapai menggunakan mobil maupun sepeda motor.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "26 Juli, 2022",
    cover: "/assets/images/UMKM/Yu_Ani_Cake.jpg",
  },
  {
    id: 9,
    subLink: "eni-dawet",
    title: "Enda",
    category: "Dawet",
    subCategory: ["Minuman", "", ""],
    owner: "Eni",
    address: "RT 01 RW 01, Dusun Krajan, Desa Gemawang",
    gmaps: "",
    ecommerce: "-",
    phone: "088225244237",
    product: "Dawet original, nangka, dan durian",
    price: "Rp5.000/bungkus",
    firstParagraph:
      "Dawet Enda merupakan salah satu UMKM yang terdapat di Desa Gemawang. Ibu Eni selaku pemilik usaha memilih nama akronim Eni Dawet menjadi Enda sebagai nama usaha beliau. Dawet yang dijual terbuat dari beberapa komposisi seperti santan, juruh, dan cendol. Beliau membuat pukul 22.00 WIB lalu menjualnya saat pagi hari. Bu Eni mulai berjualan sekitar pukul 08.00-09.00 WIB.",
    secondParagraph:
      "Pada mulanya, Ibu Eni merupakan seorang pekerja bank. Beliau kemudian berlatih kepada teman beliau dari Banjarnegara bagaimana cara membuat dawet. Beliau kemudian merintis usaha berjualan dawet hingga memiliki pasarnya. Ibu Eni biasa menjual dawetnya di Alun-alun Ambarawa. Selain itu, Ibu Eni telah memiliki langganan seperti Pusdik dan Kavaleri. Untuk menambah pemasukan, Bu Eni juga menjual bakso saat musim hujan. Dawet ayu buatan Ibu Eni dibanderol dengan harga Rp5000. Keuntungan untuk para penjualnya sebesar Rp1000. Ada beberapa jenis dawet yang dijual oleh Enda Dawet yakni dawet durian, nangka, dan original. Selain itu, dawet enda juga menerima pesanan untuk acara besar.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "26 Juli, 2022",
    cover: "/assets/images/UMKM/",
  },
  {
    id: 10,
    subLink: "tusuk-badai",
    title: "Tusuk Bambu Cap “Badai”",
    category: "Tusuk Bambu",
    subCategory: ["Tusuk Sate", "Tusuk Cilok", "Tusuk Sempol"],
    owner: "Bambang Sugiarto",
    address: "RT 03 RW 03, Dusun Banaran, Desa Gemawang",
    gmaps: "",
    ecommerce: "-",
    phone: "085771459786",
    product: "Tusuk sate, sempol, dan cilok",
    price: "Tusuk sate dan cilok Rp12.000/pak, tusuk sempol Rp10.000/pak",
    firstParagraph:
      "Tusuk sate cap “Badai” merupakan salah satu UMKM (Usaha Mikro Kecil Menengah) craft yang berlokasi di Dusun Banaran. Pemiliknya, Pak Bambang, bercerita mengenai awal terbentuknya UMKM ini dimana beliau membuat sendiri tusuk sate sedari awal hingga pengemasan dan pemasarannya. Produk yang ditawarkan antara lain tusuk sate tumpul untuk tusuk sempol dan tusuk sate lancip untuk tusuk cilok dan sate. Saat ini, Pak Bambang membeli produk dari Salatiga yang setelahnya dikeringkan dan dikemas di kediamannya.",
    secondParagraph:
      "Strategi pemasaran yang dilakukan saat ini dengan menggunakan facebook dan WhatsApp secara online juga secara langsung memasarkan ke para pedagang di Bedono dan Pingit. Untuk jangka waktu pengerjaan satu minggu, Pak Bambang bisa membuat kurang lebih 30 kg tusuk sate yang siap dipasarkan.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "26 Juli, 2022",
    cover: "/assets/images/UMKM/Tusuk_Badai.jpg",
  },
  {
    id: 11,
    subLink: "budi-karya",
    title: "Budi Karya",
    category: "Kerupuk",
    subCategory: ["Makanan"],
    owner: "Dadang Prastiyo Aji",
    address: "RT 01 RW 01, Dusun Krajan, Desa Gemawang",
    gmaps: "",
    ecommerce: "-",
    phone: "085290527614",
    product: "Kerupuk rambak mentah",
    price: "Rp6.000/pak",
    firstParagraph:
      "Kerupuk rambak budi karya merupakan salah satu usaha kerupuk rambak mentah yang berlokasi di Dusun Krajan. Usaha ini sudah berdiri sejak lama dengan nama nguripi yang menggunakan strategi pemasaran secara offline dan memiliki pelanggan tetap. Produk yang ditawarkan dari usaha ini berupa kerupuk rambak mentah yang dapat bertahan selama kurang lebih enam bulan sehingga cocok untuk dijadikan sebagai salah satu buah tangan dari Desa Gemawang.",
    secondParagraph:
      "Segala proses yang dilakukan untuk dapat membuat satu bungkus kerupuk rambak mentah yang terdiri dari pembuatan adonan dan pencetakan adonan, pemotongan, pengeringan, hingga pengemasan dilakukan di Krajan dengan mesin seperti mesin pemotong dan oven.",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "28 Juli, 2022",
    cover: "/assets/images/UMKM/Budi_Karya.jpg",
  },
  // {
  //     id: 12,
  //     subLink: "udi-roso",
  //     title: "Udi Roso",
  //     category: "Keripik",
  //     subCategory: ["Keripik singkong", "Keripik talas", "Keripik klathak"],
  //     owner: "Udi Wahyono",
  //     address: "",
  //     gmaps: "",
  //     ecommerce: "",
  //     phone: "",
  //     product: "",
  //     price: "",
  //     firstParagraph:
  //       "",
  //     secondParagraph:
  //       "",
  //     authorName: "Tim KKN Jambu JT092",
  //     authorAvatar: "/assets/images/logo.png",
  //     createdAt: " Juli, 2022",
  //     cover: "/assets/images/UMKM/",
  //   },
  {
    id: 13,
    subLink: "madu-kampung-banaran",
    title: "Madu Kampung Banaran",
    category: "Madu",
    subCategory: ["Madu murni", "Minuman"],
    owner: "Rustamaji",
    address: "RT 02 RW 02, Dusun Banaran, Desa Gemawang",
    gmaps: "https://goo.gl/maps/Qor5op4T6VbkCKmAA",
    ecommerce: "-",
    phone: "085640210637/085727819775",
    product: "Madu kemasan 140 ml dan 460 ml",
    price: "Rp40.000 untuk 140 ml dan Rp100.000 untuk 460 ml",
    firstParagraph:
      "Madu Kampung Banaran adalah satu dari sekian banyak UMKM Madu yang berdiri di Desa Gemawang khususnya di Dusun Banaran. Bu Ummi menceritakan bahwa awal mula berdirinya Madu Kampung Banaran adalah ketika beliau dititipi oleh temannya untuk membelikan madu lantaran pada saat itu di desa Gemawang sudah memiliki banyak peternak maupun penjual madu. Berawal dari hal tersebut, Bu Ummi mencoba peruntungan untuk menghasilkan madu sendiri dan memulai usaha madunya.",
    secondParagraph:
      "Produk madu yang dihasilkan diantaranya adalah madu rambutan, randu, kopi, royal jelly, dan bee pollen. Terdapat dua kemasan madu yang dipasarkan yakni Rp100.000,00 untuk madu sebanyak 460 ml dan Rp40.000,00 untuk ukuran 160 ml. Pemasaran produk Madu Kampung Banaran dilakukan melalui WhatsApp, reseller, maupun dari mulut ke mulut. ",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "28 Juli, 2022",
    cover: "/assets/images/UMKM/Madu_Kampung_Banaran.jpg",
  },
  // {
  //     id: ,
  //     subLink: "",
  //     title: "",
  //     category: "",
  //     subCategory: ["", "", ""],
  //     owner: "",
  //     address: "",
  //     gmaps: "",
  //     ecommerce: "",
  //     phone: "",
  //     product: "",
  //     price: "",
  //     firstParagraph:
  //       "",
  //     secondParagraph:
  //       "",
  //     authorName: "Tim KKN Jambu JT092",
  //     authorAvatar: "/assets/images/logo.png",
  //     createdAt: " Juli, 2022",
  //     cover: "/assets/images/UMKM/",
  //   },
  // {
  //     id: ,
  //     subLink: "",
  //     title: "",
  //     category: "",
  //     subCategory: ["", "", ""],
  //     owner: "",
  //     address: "",
  //     gmaps: "",
  //     ecommerce: "",
  //     phone: "",
  //     product: "",
  //     price: "",
  //     firstParagraph:
  //       "",
  //     secondParagraph:
  //       "",
  //     authorName: "Tim KKN Jambu JT092",
  //     authorAvatar: "/assets/images/logo.png",
  //     createdAt: " Juli, 2022",
  //     cover: "/assets/images/UMKM/",
  //   },
  // {
  //     id: ,
  //     subLink: "",
  //     title: "",
  //     category: "",
  //     subCategory: ["", "", ""],
  //     owner: "",
  //     address: "",
  //     gmaps: "",
  //     ecommerce: "",
  //     phone: "",
  //     product: "",
  //     price: "",
  //     firstParagraph:
  //       "",
  //     secondParagraph:
  //       "",
  //     authorName: "Tim KKN Jambu JT092",
  //     authorAvatar: "/assets/images/logo.png",
  //     createdAt: " Juli, 2022",
  //     cover: "/assets/images/UMKM/",
  //   },
];

export const wisata = [
  {
    id: 1,
    title: "Gunung Watu",
    desc: "Gunung Watu adalah tempat wisata alam di Desa Gemawang berupa tumpukan batu-batu besar di atas bukit. Menurut legenda, Gunung Watu terbentuk karena kutukan dari Sunan Katong kepada Paku Wojo yang telah menyalahgunakan kerisnya. Wisata ini terletak di Dusun Kerep.",
    secondDesc: "",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "24 Juli, 2022",
    cover: "/assets/images/Wisata/Gunung_Watu.png",
  },
  {
    id: 2,
    title: "Batik Losari",
    desc: "Di bawah Yayasan Losari, Batik Losari mulai memproduksi batik tulis dengan warna alami sejak 2006. Studio batik pertama yang dimiliki adalah Omah Batik Jlamprang yang terletak di Jlamprang, Gemawang. Batik Losari memilih filosofi tanaman atau objek di sekitar untuk motif batik tulis yang dibuat. Identitas dari Batik Losari adalah “women, culture and nature”.",
    secondDesc: "",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: "26 Juli, 2022",
    cover: "/assets/images/Wisata/Batik_Losari.jpg",
  },
];

export const kesenian = [
  {
    id: 1,
    title: "Topeng Ireng dan Kewanan",
    first:
      "Ada yang mengatakan jika Tari Topeng Ireng berawal dari Desa Tuksongo, Kecamatan Borobudur, Kabupaten Magelang, Jawa Tengah yang menggambarkan sekelompok prajurit melawan penjajah Belanda saat itu. Dahulu Topeng Ireng disebut dengan Dayakan karena menggunakan pakaian yang mirip dengan pakaian khas Dayak. Karena dikhawatirkan terdapat unsur SARA di kata Dayakan, maka pada pemerintahan Soeharto, Dayakan diubah namanya menjadi Topeng Ireng. Topeng Ireng merupakan singkatan dari Toto Lempeng Irama Kenceng. Kalimat tersebut memiliki makna, Toto berarti menata, Lempeng berarti lurus, Irama berarti nada, dan Kenceng berarti keras, sehingga dapat diartikan sebagai tarian yang para penarinya berbaris lurus dengan irama yang cepat. Topeng Ireng mengkombinasikan ilmu bela diri pencak silat dan syiar agama Islam, serta juga menggambarkan kehidupan masyarakat lereng Gunung Merapi dan Merbabu yang hidup berdampingan atau akrab dengan alam. Topeng Ireng biasa digunakan dalam acara nyadran, mertri desa atau bersih desa, acara karnaval atau hajatan, dan acara lainnya.",
    second:
      "Topeng Ireng dan Kewanan menceritakan masyarakat yang hendak menebang hutan untuk membangun desa. Kemudian diadakan syukuran atas pembangunan desa tersebut dan dinamakanlah Dayakan yang sekarang berubah menjadi Topeng Ireng. Hewan-hewan yang ada di hutan hendak menyerang, akan tetapi terdapat salah satu orang sakti yang bisa mengalahkan hewan-hewan tersebut. Dari hal tersebutlah muncul cerita Topeng Ireng dan Kewanan.",
    third:
      "Topeng Ireng dan Kewanan memiliki ciri khas pada pakaian maupun aksesoris yang dikenakan. Pada Topeng Ireng terdapat aksesoris tangan dan lengan, badong yang digunakan untuk atasan, sayak yang digunakan untuk bawahan menyerupai rok, dan krincingan kaki. Sedangkan Kewanan menggunakan kostum berbagai warna, seperti putih, kuning, oranye, hitam, serta menggunakan topeng yang menggambarkan hewan, seperti topeng warak, kebo, dan lain-lain.",
    fourth:
      "Jumlah pemain Topeng Ireng dan Kewanan adalah sekitar 12 orang dengan durasi pertunjukan Topeng Ireng sekitar 30 menit kemudian dilanjutkan Kewanan sekitar 20 menit. Adapun pemainnya merupakan anak-anak usia SMP, SMA, maupun orang dewasa yang ada di desa. Persiapan untuk melakukan sebuah pertunjukan biasanya dilakukan sebulan sebelum pertunjukan dilaksanakan. Persiapan yang cukup lama tersebut diperlukan karena tarian atau formasi setiap pertunjukan bisa berbeda sehingga membutuhkan waktu untuk membuatnya. Pertunjukan Topeng Ireng dan Kewanan tetap menggunakan instrumen, seperti gendang, jidor, angklung, dan lain-lain agar nuansa klasiknya tidak hilang. ",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: " Juli, 2022",
    cover: "/assets/images/Kesenian/TopengIreng/Topeng Ireng 1.jpg",
    img: [
      "/assets/images/Kesenian/TopengIreng/Topeng Ireng 1.jpg",
      "/assets/images/Kesenian/TopengIreng/Topeng Ireng 2.jpg",
      "/assets/images/Kesenian/TopengIreng/Topeng Ireng 3.jpg",
    ],
  },
  {
    id: 2,
    title: "Kubro Siswo",
    first:
      "Tari Kubro Siswo berawal dan berkembang dari sekitar daerah Kabupaten Magelang, Jawa Tengah. Kata Kubro Siswo merupakan singkatan dari Ubahing Badan lan Rogo yang berarti “kesenian mengenai gerak badan dan jiwa” atau mengingatkan untuk selalu seimbang dalam kehidupan dunia dan akhirat. Kubro Siswo adalah kesenian yang menggambarkan semangat perjuangan bangsa dalam menghadapi penjajah Belanda dan juga digunakan untuk menyebarkan agama Islam. Kubro Siswo biasanya digunakan dalam acara hajatan, bersih desa, acara-acara ketika bulan Ramadhan, dan acara-acara lainnya.",
    second:
      "Kubro Siswo memiliki ciri khas pada kostumnya, seperti halnya terdapat selempang yang dikenakan pemain dan hal tersebut menggambarkan prajurit. Selain itu, juga terdapat beberapa instrumen musik tradisional, seperti bende, kendang, bedug, dan lain-lain sehingga tetap mempertahankan unsur klasiknya. ",
    third:
      "Dahulu kesenian Kubro Siswo bernama seni Rodat. Kubro Siswo Nurul Huda memiliki pemain yang tidak terbatas oleh usia asalkan masih mampu dan mau bermain pertunjukan.  Saat ini para pemainnya masih didominasi oleh laki-laki. Jumlah pemain Kubro Siswo sendiri berkisar antara 24 orang dengan durasi sekitar 30 menit untuk satu kali pertunjukan. Sebagai persiapan, diperlukan setidaknya latihan hingga dua kali pertemuan sebelum pertunjukan dilaksanakan. Kubro Siswo sendiri sudah tampil di beberapa tempat di wilayah Semarang, Gedong Songo, Jepara, hingga Kediri.",
    fourth: "",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: " Juli, 2022",
    cover: "/assets/images/Kesenian/KubroSiswo/Kubro Siswo 1.jpeg",
    img: [
      "/assets/images/Kesenian/KubroSiswo/Kubro Siswo 1.jpeg",
      "/assets/images/Kesenian/KubroSiswo/Kubro Siswo 2.jpeg",
      "/assets/images/Kesenian/KubroSiswo/Kubro Siswo 3.jpeg",
    ],
  },
  {
    id: 3,
    title: "Wisanggeni Angklung",
    first:
      "Angklung Wisanggeni sudah ada sejak tahun 2018 dan sudah tampil di beberapa daerah, seperti Semarang, Magelang, dan Temanggung. Angklung Wisanggeni biasanya tampil untuk meramaikan acara-acara, seperti acara hajatan, khitanan, dan lain-lain.",
    second:
      "Jumlah pemain untuk setiap pertunjukan adalah berkisar antara delapan orang. Untuk setiap pertunjukan biasanya memiliki durasi tergantung pada lagu yang dibawakan. Tidak ada lagu khusus yang digunakan, namun fleksibel pada lagu apapun, seperti lagu pop, dangdut, campursari, dan jenis lagu lainnya. Angklung Wisanggeni biasanya mengadakan latihan sekali setiap minggunya dan apabila akan ada pertunjukan maka membutuhkan latihan sebanyak dua kali pertemuan.",
    third:
      "Angklung Wisanggeni menggunakan beberapa alat musik, diantaranya angklung, tripok, selo angklung, bass, ritem, dan bass dem.",
    fourth: "",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: " Juli, 2022",
    cover: "/assets/images/Kesenian/Wisanggeni/Wisanggeni 1.jpeg",
    img: [
      "/assets/images/Kesenian/Wisanggeni/Wisanggeni 1.jpeg",
      "/assets/images/Kesenian/Wisanggeni/Wisanggeni 2.jpeg",
      "/assets/images/Kesenian/Wisanggeni/Wisanggeni 3.jpeg",
    ],
  },
  {
    id: 4,
    title: "Carang Turonggo Reog",
    first:
      "Carang Turonggo merupakan kesenian reog yang sudah ada sejak 1986. Carang Turonggo sendiri juga sudah tampil di beberapa daerah di Kabupaten Semarang dan biasanya tampil untuk berbagai acara, seperti hajatan hingga selamatan desa.",
    second:
      "Jumlah pemain untuk sekali pertunjukan adalah sekitar delapan orang dan masih didominasi oleh laki-laki. Ketika akan ada acara atau hendak tampil, perlu setidaknya waktu dua minggu untuk persiapan. Pemainnya sendiri berasal dari berbagai usia, ada yang berusia SD hingga orang dewasa. Ada berbagai macam tarian yang biasanya dipentaskan oleh Carang Turonggo, antara lain Tari Pedang, Tari Pegon, Tari Warok, dan Tari Kosek.",
    third:
      "Peralatan yang digunakan adalah menggunakan alat musik gamelan, seperti saron, bonang, gong, kempul, kenong, dan lain-lain. Selain itu, beberapa peralatan lain, seperti properti kuda lumping, gapura, atau topeng barongan.",
    fourth: "",
    authorName: "Tim KKN Jambu JT092",
    authorAvatar: "/assets/images/logo.png",
    createdAt: " Juli, 2022",
    cover: "/assets/images/Kesenian/Reog/Reog 1.jpeg",
    img: [
      "/assets/images/Kesenian/Reog/Reog 1.jpeg",
      "/assets/images/Kesenian/Reog/Reog 2.jpeg",
      "/assets/images/Kesenian/Reog/Reog 3.jpeg",
    ],
  },
];
